// SPDX-License-Identifier: Apache-2.0
// CECE — Chemical Emissions Coupling Engine
// Copyright (c) HELM Project Contributors

#ifndef CECE_UTC_GRID_HPP
#define CECE_UTC_GRID_HPP

#include <cstdint>
#include <string>
#include <vector>

namespace cece {

/**
 * @brief Grid constants for the static UTC-offset raster (data/utc_grid_f1440.rle).
 *
 * The grid is a 0.125° global raster of signed UTC offsets in 15-minute units,
 * laid out North→South, West→East at cell centers. It is generated by
 * scripts/python/utcoffset_generator.py from a timezone database snapshot.
 */
inline constexpr int kUtcGridRows = 1440;                          ///< 180° / 0.125°
inline constexpr int kUtcGridCols = 2880;                          ///< 360° / 0.125°
inline constexpr int kUtcGridCells = kUtcGridRows * kUtcGridCols;  ///< 4,147,200
inline constexpr double kUtcGridStepDeg = 0.125;                   ///< Cell size in degrees
inline constexpr int kUtcOffsetQuarterHoursPerSecond = 900;        ///< 15 minutes in seconds

/**
 * @brief Decode the RLE-compressed UTC-offset grid file into a dense int8 field.
 *
 * The file is a headerless sequence of little-endian 3-byte tokens
 * `(uint16_t run_length, int8_t offset_15min)`; each token expands to
 * `run_length` copies of `offset_15min`, laid out N→S / W→E at 0.125° cell
 * centers (row-major, index = row * 2880 + col).
 *
 * All-or-nothing: a file whose expanded length does not equal 1440×2880 is
 * rejected wholesale — a partially-populated grid must never mask real
 * offsets as 0 (spec FR-003, FR-008).
 *
 * @param path Path to the .rle file.
 * @return Dense grid of size kUtcGridCells, values in [-128, 127] quarter-hours.
 * @throws std::runtime_error if the file cannot be opened, read, or the
 *         decoded length does not equal kUtcGridCells.
 */
std::vector<std::int8_t> DecodeUtcGridRle(const std::string& path);

/**
 * @brief Resolve the F1440 row index for a latitude (cell-center floor mapping).
 *
 * row = clamp(floor((90 - lat) / 0.125), 0, 1439). This is the exact inverse
 * of the generator's cell-center rasterization (lat = 90 - (row+0.5)*0.125)
 * and selects the containing (nearest) cell for any point.
 */
int UtcGridRowForLat(double lat);

/**
 * @brief Resolve the F1440 column index for a longitude (cell-center floor mapping).
 *
 * col = clamp(floor(mod(lon + 180, 360) / 0.125), 0, 2879). The modulo wraps
 * 0..360 conventions; clamping covers ±90°/±180° edge inputs.
 */
int UtcGridColForLon(double lon);

/**
 * @brief Map the dense F1440 grid onto the native simulation grid, band-local.
 *
 * For each native cell (i, j_global = j0 + j), performs a nearest-grid-cell
 * lookup (no interpolation, spec FR-004) and converts the int8 quarter-hour
 * offset to int32 seconds. Output is band-local to match the stacking kernel's
 * (i, j) indexing (research D2): out[i + j * nx], j in [0, ny_local).
 *
 * @param grid          Dense decoded F1440 grid (size kUtcGridCells).
 * @param native_lons   1-D longitude coordinate array (size nx), degrees.
 * @param native_lats   1-D latitude coordinate array (size ny global), degrees.
 * @param nx            Native grid x extent.
 * @param j0            Global latitude index of this rank's first row.
 * @param ny_local      Number of latitude rows this rank owns.
 * @return Band-local offsets in seconds, size nx * ny_local.
 * @throws std::invalid_argument on size mismatch (grid extent, coordinate arrays).
 */
std::vector<std::int32_t> MapToNativeOffsetsSec(const std::vector<std::int8_t>& grid, const std::vector<double>& native_lons,
                                                const std::vector<double>& native_lats, int nx, int j0, int ny_local);

}  // namespace cece

#endif  // CECE_UTC_GRID_HPP
